---
title: Postdoc position available!
authors:
  - ch153
date: '2019-08-01'
slug: lab-openings
categories:
  - 'lab news'
tags:
  - 'lab news'
summary: 'We are looking for a postdoc scientist to work on our recently funded NSF Plant Genome project.'
---

### We are looking for a postdoc scientist to work on our recently funded NSF Plant Genome project.

[Complete posting in PDF](/files/jobs/Huang_Lab_postdoc_June2019_interfolio_official_2.pdf)

### Location
NYU Center for Genomics and Systems Biology - 12 Waverly Place, New York, NY 10003

### Open Date
Jul 29, 2019

### Description 
The Huang lab at NYU Biology (https://huanglab.rbind.io/) is looking for a highly motivated and independent
individual to work as a Postdoctoral Associate. This position is for a post-PhD trainee preparing for a career path
in research. The planned position will provide a transition to career independence through the development of
professional skills; supervision by faculty mentor incorporating individual development plan in support of
training goals and those of the faculty mentor; and publication of research findings/scholarship during postdoc
appointment period. We aim to build a highly interdisciplinary and collaborative lab, and are committed to
provide a supportive environment for lab members to achieve scientific excellence and gain expertise in both
computational and experimental skills.

Projects in the Huang lab use both “dry”- and “wet”-lab genomics methods to study gene regulation at the
systems level. Specifically, we are interested in understanding how the within-species genome and epigenome
variation gives rise to variation in the regulatory networks that underlie phenotypic variation. We work with the
reference plant Arabidopsis and collaborate with multiple groups working on agriculturally and ecologically
important plants. The planned project is recently funded by the NSF for theoretical and experimental
development of the DNA affinity purification sequencing (DAPseq) technique for mapping and characterization
of cis-regulatory variation in plant genomes.

### Qualifications
The ideal candidate will hold a PhD with expertise in any of the areas below, as evidenced by first-author or co-
first-author publications: plant biology, molecular biology, genetics/genomics, ecology/evolution, or
computational biology. Relevant skills and experience include molecular cloning, protein expression and
purification, next generation sequencing technologies, single cell genomics, comparative genomics, analysis of
high-throughput sequencing data, basic statistics, computer programming and/or machine learning. Experience
with Arabidopsis and/or plant genome editing is a plus. The position is expected to continue for multiple years
contingent on satisfactory performance.

### Application Instructions
Please submit a cover letter, resume and contact information for three references to
https://apply.interfolio.com/66068.
