---
title: Postdoc position available! (November 2020)
date: '2020-11-29'
slug: lab-openings-nsf-nih
categories:
  - lab news
tags:
  - lab news
subtitle: ''
summary: 'We are looking for a postdoc scientist with experience in regulatory genomics for projects supported by our NSF Plant Genomes and NIH R35/MIRA awards.'
authors: [ch153]

lastmod: '2020-11-29T01:28:23-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

### We are looking for a postdoc scientist with experience in regulatory genomics for projects supported by our NSF Plant Genomes and NIH R35/MIRA awards.

[Complete posting in PDF](/files/jobs/Huang_Lab_postdoc_Nov2020_interfolio_official.pdf)

### Location
NYU Center for Genomics and Systems Biology - 12 Waverly Place, New York, NY 10003

### Open Date
Nov 6, 2020

### Description 
The Huang lab at NYU Biology (huanglab.rbind.io) is looking for a highly motivated and independent individual to work as a Postdoctoral Associate in regulatory genomics.


This position is for a post-PhD trainee preparing for a research scientist career path. The planned position will provide a transition to career independence through the development of professional skills; supervision by senior scientist incorporating individual development plan in support of training goals and those of faculty mentor; and publication of research findings/scholarship during postdoc appointment period.

Projects in the Huang lab use both "dry"- and "wet"-lab genomics methods to study gene regulation at the systems level. This position is funded by the lab?s research grants from the NIH and NSF that aim to develop and apply the DAP-seq (DNA affinity purification-sequencing) method to characterize natural variation in transcription factor - DNA interactions and use computational modelling to understand the regulatory functions of genome and epigenome variation. We work with the reference plant Arabidopsis and collaborate with multiple groups on agriculturally and ecologically important plants.

We aim to build a highly interdisciplinary and collaborative lab, and are committed to provide a supportive environment for lab members to achieve scientific excellence and gain expertise in both computational and experimental skills. The lab space is centrally located in the Washington Square campus of NYU at the Center for Genomics and Systems Biology.


### Qualifications
The ideal candidate will hold a PhD in genetics/genomics, molecular biology, plant biology, ecology/evolution or computational biology, a track record or first- or co-first-author peer-reviewed publications, and prior research experience in any of these areas: molecular cloning, protein expression and purification, comparative genomics, analysis of high-throughput sequencing data, basic statistics, computer programming and/or machine learning. Experience with working with Arabidopsis or analyzing plant genome sequences is a plus. The position is expected to continue for multiple years contingent on satisfactory performance.

### Application Instructions
Please upload your application materials via Interfolio at https://apply.interfolio.com/80828. Include the following items: 1) CV including a list of publications; 2) cover letter with brief description of your present and future research interests; 3) a list of three references and their contact information.


